POST http://localhost:8000/bands/
Content-Type: application/json

{
  "name": "Faith no More2",
  "genre": "rock"
}

###
GET http://localhost:8000/bands/
Content-Type: application/json

###
GET http://127.0.0.1:8000/bands?genre=metal&has_albums=true
Content-Type: application/json

###
POST http://localhost:8000/bands/
Content-Type: application/json

{
  "name": "Gojira",
  "genre": "Metal",
  "albums": [
    {
      "title": "Magma",
      "release_date": "2016-06-17"
    }
  ]
}
